name: Deploy

on:
  push:
    branches:
      - main

env:
  SHA: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_KEY }}
          heroku_app_name: 'servo-dashboard'
          heroku_email: 'fredrik@peteri.se'
